// Référentiel officiel des départements et communes d'Haïti,
// utilisé pour les sélecteurs en cascade (département -> ville)
// dans les formulaires d'ajout de clinique / pharmacie.

export const HAITI_DEPARTMENTS_CITIES: Record<string, string[]> = {
  Artibonite: [
    'Dessalines',
    'Desdunes',
    'Grande-Saline',
    "Petite-Rivière-de-l'Artibonite",
    'Gonaïves',
    'Ennery',
    "L'Estère",
    'Gros-Morne',
    'Anse-Rouge',
    'Terre-Neuve',
    'Marmelade',
    "Saint-Michel-de-l'Atalaye",
    'Saint-Marc',
    'La Chapelle',
    'Liancourt',
    'Verrettes',
    'Montrouis',
  ],
  Centre: [
    'Cerca-la-Source',
    'Thomassique',
    'Hinche',
    'Cerca-Carvajal',
    'Maïssade',
    'Thomonde',
    'Lascahobas',
    'Baptiste',
    'Belladère',
    'Savanette',
    'Mirebalais',
    'Boucan-Carré',
    "Saut-d'Eau",
  ],
  "Grand'Anse": [
    "Anse-d'Hainault",
    'Dame-Marie',
    'Les Irois',
    'Beaumont',
    'Corail',
    'Pestel',
    'Roseaux',
    'Jérémie',
    'Abricots',
    'Bonbon',
    'Chambellan',
    'Marfranc',
    'Moron',
  ],
  Nippes: [
    'Anse-à-Veau',
    'Arnaud',
    "L'Asile",
    'Petit-Trou-de-Nippes',
    'Plaisance-du-Sud',
    'Baradères',
    'Grand-Boucan',
    'Miragoâne',
    'Fonds-des-Nègres',
    'Paillant',
    'Petite-Rivière-de-Nippes',
  ],
  Nord: [
    'Acul-du-Nord',
    'Milot',
    'Plaine-du-Nord',
    'Borgne',
    'Port-Margot',
    'Cap-Haïtien',
    'Limonade',
    'Quartier-Morin',
    'Grande-Rivière-du-Nord',
    'Bahon',
    'Limbé',
    'Bas-Limbé',
    'Plaisance',
    'Pilate',
    'Saint-Raphaël',
    'Dondon',
    'La Victoire',
    'Pignon',
    'Ranquitte',
  ],
  'Nord-Est': [
    'Fort-Liberté',
    'Ferrier',
    'Perches',
    'Ouanaminthe',
    'Capotille',
    'Mont-Organisé',
    'Trou-du-Nord',
    'Caracol',
    'Sainte-Suzanne',
    'Terrier-Rouge',
    'Vallières',
    'Carice',
    'Mombin-Crochu',
  ],
  'Nord-Ouest': [
    'Môle-Saint-Nicolas',
    'Baie-de-Henne',
    'Bombardopolis',
    'Jean-Rabel',
    'Port-de-Paix',
    'Bassin-Bleu',
    'Chansolme',
    'La Tortue',
    'La Pointe',
    'Saint-Louis-du-Nord',
    'Anse-à-Foleur',
  ],
  Ouest: [
    'Arcahaie',
    'Cabaret',
    'Croix-des-Bouquets',
    'Cornillon',
    'Fonds-Verrettes',
    'Ganthier',
    'Thomazeau',
    'Anse-à-Galets',
    'Pointe-à-Raquette',
    'Léogâne',
    'Grand-Goâve',
    'Petit-Goâve',
    'Port-au-Prince',
    'Carrefour',
    'Cité Soleil',
    'Delmas',
    'Gressier',
    'Kenscoff',
    'Pétion-Ville',
    'Tabarre',
  ],
  'Sud-Est': [
    'Bainet',
    'Côtes-de-Fer',
    'Belle-Anse',
    'Anse-à-Pitres',
    'Grand-Gosier',
    'Thiotte',
    'Jacmel',
    'Cayes-Jacmel',
    'La Vallée-de-Jacmel',
    'Marigot',
  ],
  Sud: [
    'Aquin',
    'Cavaillon',
    'Saint-Louis-du-Sud',
    'Fond-des-Blancs',
    'Les Cayes',
    'Camp-Perrin',
    'Chantal',
    'Île-à-Vache',
    'Maniche',
    'Torbeck',
    'Chardonnières',
    'Les Anglais',
    'Tiburon',
    'Côteaux',
    'Port-à-Piment',
    'Roche-à-Bateau',
    'Port-Salut',
    'Arniquet',
    'Saint-Jean-du-Sud',
  ],
};

export const HAITI_DEPARTMENTS = Object.keys(HAITI_DEPARTMENTS_CITIES);

export function citiesForDepartment(department: string): string[] {
  return HAITI_DEPARTMENTS_CITIES[department] ?? [];
}